routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('user.register');
});
Route::post('/', 'UserController@register')->name('register');

Route::get('login', function () {
    return view('user.login');
})->name('login');
Route::post('login', 'UserController@login')->name('login-final');

Route::group(['middleware' => 'auth'], function(){
	Route::get('/list', 'UserController@index')->name('category.list');
	Route::get('add-category', 'UserController@add')->name('add-category');
	Route::post('create-category', 'UserController@create')->name('create-category');
	Route::get('edit-category/{id}', 'UserController@edit')->name('edit-category');
	Route::post('update-category/{id}', 'UserController@update')->name('update-category');
	Route::get('delete-data/{id}', 'UserController@delete')->name('delete-category');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function subCategories(){
    	return $this->hasMany(Category::class, 'parent_id', 'id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\User;
use App\Category;

class UserController extends Controller
{
    public function register(Request $request){
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'mobile' => 'required|numeric|unique:users,mobile',
            'password' => 'required|min:6|confirmed',
        ]);

        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->mobile = $request->mobile;
        $user->password = bcrypt($request->password);
        $user->save();

        return redirect()->route('login')->with('message', 'Registered Successfully.');
    }

    public function login(Request $request){
        $this->validate($request, [
            'email' => 'required|email|exists:users,email',
            'password' => 'required',
        ]);

        if(Auth::attempt(['email' => $request->email, 'password' => $request->password])){
            return redirect()->route('category.list');
        }else{
            return redirect()->back()->with('error', 'Email and Password does not match.');
        }
    }

    public function index(Request $request){
        // dd($request);
    	$categories = Category::orderBy('id', 'desc');
        if(!isset($request->category) && $request->category == null){
            $categories = $categories->whereNull('parent_id');
            $parent_detail = '';
        }else{
            $categories = $categories->where('parent_id', $request->category);
            $parent_detail = Category::where('id', $request->category)->first();
        }
        $categories = $categories->withCount('subCategories')->paginate(10);
        // dd($categories);
    	return view('user.info', compact('categories', 'parent_detail'));
    }

    public function add(){
        if(!isset(request()->category) && request()->category == null){
            $parent_detail = '';
        }else{
            $parent_detail = Category::where('id', request()->category)->first();
        }
    	return view('user.add', compact('parent_detail'));
    }

    public function create(Request $request){
    	$this->validate($request, [
    		'name' => 'required|unique:categories,name',
    		'image' => 'required|image|mimes:jpg,png,jpeg,gif,webp,svg|max:300|dimensions:min_width=100,min_height=100,max_width=1500,max_height=1500',
    	]);

        if(isset($request->parent_id) && $request->parent_id != null){
            $check = Category::where('id', $request->parent_id)->first();
            if($check == null){
                return redirect()->back()->with('error', 'Parent Category does not exists');
            }
        }

    	$query = new Category();
    	$query->name = $request->name;
    	if($request->hasFile('image')){
    		$path = 'storage/'.$request->file('image')->store('profile-pic/'.date('d-m-Y'));
    		$query->image = $path;
    	}
        $query->parent_id = $request->parent_id;
    	$query->save();
        return redirect()->route('category.list',['category' => $request->parent_id])->with('message', 'Created Successfully.');
    }

    public function edit($id){
    	$check = Category::where('id', $id)->first();
    	if($check == null){
    		return redirect()->back()->with('error', 'Data does not exists.');
    	}
    	return view('user.edit', compact('check'));
    }

    public function update(Request $request, $id){
        $check = Category::where('id', $id)->first();
        if($check == null){
            return redirect()->back()->with('error', 'Data does not exists.');
        }

        $this->validate($request, [
            'name' => 'required|unique:categories,name',
            'image' => 'nullable|image|mimes:jpg,png,jpeg,gif,webp,svg|max:300|dimensions:min_width=100,min_height=100,max_width=1500,max_height=1500',
        ]);

    	$query = $check;
        $query->name = $request->name;
        if($request->hasFile('image')){
            $path = 'storage/'.$request->file('image')->store('profile-pic/'.date('d-m-Y'));
            $query->image = $path;
        }
        $query->parent_id = $request->parent_id;
        $query->save();

    	return redirect()->route('category.list',['category' => request()->input('category')])->with('message', 'Category Updated Successfully.');
    }

    public function delete($id){
        $check = Category::where('id', $id)->first();
        if($check == null){
            return redirect()->back()->with('error', 'Data does not exists.');
        }

    	$check->delete();
    	return redirect()->route('category.list',['category' => request()->input('category')])->with('message', 'Data Deleted Successfully.');
    }
}

resources/views/layouts/user.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Tripster @yield('title')</title>
        @include('user.partials.head-new')

        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.css">
    </head>

    <body data-baseurl="{{asset('/')}}">
        <div class="container-scroller">
            <!-- partial:../../partials/_navbar.html -->
            @include('user.partials.header-new')
            <!-- partial -->
            <div class="container-fluid page-body-wrapper">
                <!-- partial:../../partials/_sidebar.html -->
                @include('user.partials.sidebar-new')
                <!-- partial -->
                <div class="main-panel">
                    <div class="content-wrapper">
                        @yield('content')
                    </div>
                    <!-- content-wrapper ends -->
                    <!-- partial:../../partials/_footer.html -->
                    <footer class="footer">
                        <div class="d-sm-flex justify-content-center justify-content-sm-between">
                            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2020 <a href="https://www.bootstrapdash.com/" target="_blank">Tripster</a>. All rights reserved.</span>
                            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
                        </div>
                    </footer>
                    <!-- partial -->
                </div>
                <!-- main-panel ends -->
            </div>
            <!-- page-body-wrapper ends -->
        </div>
        <!-- container-scroller -->
        <!-- plugins:js -->
        @include('user.partials.footerScripts-new')

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.js"></script>
        
        @yield('scripts')
    </body>

</html>

resources/views/user/add.blade.php
@extends('layouts.user')
@section('title', 'Category List')

@section('content')
    @if($errors->count() > 0)
        @foreach($errors->all() as $error)
            <p class="alert alert-danger">{{$error}}</p>
        @endforeach
    @endif
    @if(Session::has('message'))
        <div class="alert alert-success"> {{Session::get('message')}}</div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger"> {{Session::get('error')}}</div>
    @endif
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                @if($parent_detail == null)
                    <h4 class="card-title">Add Category</h4>
                @else
                    <h4>Add Sub-Category for {{ $parent_detail->name }}</h4>
                @endif
                <p class="card-description">
                    <!-- Add class <code>.table-striped</code> -->
                </p>
                <form action="{{ route('create-category') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="parent_id" value="{{ request()->input('category') }}">
                    <div class="form-group">
                        <label for="f_name">Name:</label>
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                    </div>
                    <div class="form-group">
                        <label for="f_name">Choose Pic:</label>
                        <input type="file" class="form-control" name="image" id="image">
                    </div>
                    <button type="submit" class="btn btn-default" id="form-submit">Submit</button>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

@endsection

resources/views/user/edit.blade.php
@extends('layouts.user')
@section('title', 'User List')

@section('content')
    @if($errors->count() > 0)
        @foreach($errors->all() as $error)
            <p class="alert alert-danger">{{$error}}</p>
        @endforeach
    @endif
    @if(Session::has('message'))
        <div class="alert alert-success"> {{Session::get('message')}}</div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger"> {{Session::get('error')}}</div>
    @endif
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Edit</h4>
                <p class="card-description">
                    <!-- Add class <code>.table-striped</code> -->
                </p>
                <form action="{{ route('update-category',$check->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">
                        <label for="f_name">Name:</label>
                        <input type="text" class="form-control" name="name" value="{{ $check->name }}">
                    </div>

                    <div class="form-group">
                        <img src="{{ asset($check->image) }}">
                        <label for="f_name">Choose Pic:</label>
                        <input type="file" class="form-control" name="image" id="image">
                    </div>

                    <button type="submit" class="btn btn-default">Update</button>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
<script>
    var base_url = $('body').attr('data-baseurl');
</script>
@endsection

resources/views/user/info.blade.php
@extends('layouts.user')
@section('title', 'User List')

@section('content')
    @if($errors->count() > 0)
        @foreach($errors->all() as $error)
            <p class="alert alert-danger">{{$error}}</p>
        @endforeach
    @endif
    @if(Session::has('message'))
        <div class="alert alert-success"> {{Session::get('message')}}</div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger"> {{Session::get('error')}}</div>
    @endif
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="col-lg-12">
            </div>
            <br>
            <div class="col-lg-12">
            </div>
            
            <div class="card-body table-responsive">
                @if($parent_detail == null)
                    <a href="{{ route('add-category') }}" class="btn btn-warning" style="float: right;">Add Category </a>
                @else
                    <a href="{{ route('add-category', ['category' => $parent_detail->id]) }}" class="btn btn-warning" style="float: right;">Add Sub-Category for {{ $parent_detail->name }} </a>
                @endif

                <h4 class="card-title">List</h4>
                <p class="card-description">
                    <!-- Add class <code>.table-striped</code> -->
                </p>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>S.No.</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Number Of Suc Cat</th>
                            <th>Time</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if($categories->count() > 0)
                            @foreach($categories as $key => $value)
                                <tr>
                                    <td>{{ $loop->index+1 }}</td>
                                    <td>{{ $value->name }}</td>
                                    <td>
                                        <a href="{{ asset($value->image) }}" target="_blank">View</a>
                                    </td>
                                    <td>{{ $value->sub_categories_count }}</td>
                                    <td>{{ $value->created_at }}</td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-primary dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">Action
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="menu1">

                                                <li role="presentation">
                                                    <a role="menuitem" tabindex="-1" href="{{ route('category.list', ['category' => $value->id]) }}"><span class="fa fa-pencil-square-o"></span> View</a>
                                                </li>

                                                <li role="presentation">
                                                    <a role="menuitem" tabindex="-1" href="{{ route('edit-category',$value->id) }}"><span class="fa fa-pencil-square-o"></span> Edit</a>
                                                </li>

                                                <li role="presentation">
                                                    <a role="menuitem" tabindex="-1" href="{{ route('delete-category',$value->id) }}"><span class="fa fa-trash"></span> Delete</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="10" style="text-align: center; font-size: 30px;">No Details Available </td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            {{$categories->appends(request()->input())->links()}}
        </div>
    </div>

@endsection

@section('scripts')

@endsection

resources/views/user/login.blade.php
<!DOCTYPE html>
<html lang="en">

	<head>
	  	<!-- Required meta tags -->
	  	<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Task Admin</title>
		<!-- plugins:css -->
	  	<link rel="stylesheet" href="{{asset('adminasset/vendors/iconfonts/mdi/css/materialdesignicons.min.css')}}">
	  	<link rel="stylesheet" href="{{asset('adminasset/vendors/css/vendor.bundle.base.css')}}">
	  	<!-- endinject -->
	  	<!-- plugin css for this page -->
	  	<!-- End plugin css for this page -->
	  	<!-- inject:css -->
	  	<link rel="stylesheet" href="{{asset('adminasset/css/style.css')}}">
	  	<!-- endinject -->
	  	<link rel="shortcut icon" href="{{asset('adminasset/images/favicon.png')}}" />

	  	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.css">
	</head>

	<body base-url="{{ asset('/') }}">
	  	<div class="container-scroller">
			<div class="container-fluid page-body-wrapper full-page-wrapper">
			  	<div class="content-wrapper d-flex align-items-center auth">
					<div class="row w-100">
					  	<div class="col-lg-4 mx-auto">
							<div class="auth-form-light text-left p-5">
							  	<div class="brand-logo">
									<!-- <img src="{{asset('adminasset/images/logo.svg')}}"> -->
							  	</div>
							  	<h4>Task : User</h4>
							  	<h6 class="font-weight-light">Sign in to continue.</h6>
							  	<form class="pt-3" method="POST" action="{{ route('login-final') }}" >
									@csrf
									<div class="form-group">
									  	<input type="email" name="email" class="form-control form-control-lg" id="exampleInputEmail1" placeholder="Username">
									  	@if($errors->has('email'))
									  	<small id="passwordHelp" class="text-danger">
							              	{{$errors->first('email')}}
							            </small>
							            @endif
									</div>
									<div class="form-group">
									  	<input type="password" name="password" class="form-control form-control-lg" id="exampleInputPassword1" placeholder="Password">
									  	@if($errors->has('password'))
									  	<small id="passwordHelp" class="text-danger">
							              	{{$errors->first('password')}}
							            </small>
							            @endif
									</div>
									<div class="mt-3">
									  	<input type="submit" class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" id="form-submit" name="" value="SIGN IN">
									</div>
							  	</form>
							</div>
					  	</div>
					</div>
			  	</div>
			  <!-- content-wrapper ends -->
			</div>
		<!-- page-body-wrapper ends -->
	  	</div>
	  	<!-- container-scroller -->
	  	<!-- plugins:js -->
	  	<script src="{{asset('adminasset/vendors/js/vendor.bundle.base.js')}}"></script>
	  	<script src="{{asset('adminasset/vendors/js/vendor.bundle.addons.js')}}"></script>
	  	<!-- endinject -->
	  	<!-- inject:js -->
	 	<script src="{{asset('adminasset/js/off-canvas.js')}}"></script>
	  	<script src="{{asset('adminasset/js/misc.js')}}"></script>

	  	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.js"></script>
	  	<!-- endinject -->
	</body>

</html>

resources/views/user/partials/footerScripts-new.blade.php
<script src="{{asset('adminasset/vendors/js/vendor.bundle.base.js')}}"></script>
	<script src="{{asset('adminasset/vendors/js/vendor.bundle.addons.js')}}"></script>
	<!-- endinject -->
	<!-- Plugin js for this page-->
	<!-- End plugin js for this page-->
	<!-- inject:js -->
	<script src="{{asset('adminasset/js/off-canvas.js')}}"></script>
	<script src="{{asset('adminasset/js/misc.js')}}"></script>
	<!-- endinject -->
	<!-- Custom js for this page-->
	<!-- End custom js for this page-->

resources/views/user/partials/head-new.blade.php
<!-- plugins:css -->
	<link rel="stylesheet" href="{{asset('adminasset/vendors/iconfonts/mdi/css/materialdesignicons.min.css')}}">
	<link rel="stylesheet" href="{{asset('adminasset/vendors/css/vendor.bundle.base.css')}}">
	<!-- endinject -->
	<!-- plugin css for this page -->
	<!-- End plugin css for this page -->
	<!-- inject:css -->
	<link rel="stylesheet" href="{{asset('adminasset/css/style.css')}}">
	<!-- endinject -->
	<link rel="shortcut icon" href="{{asset('adminasset/images/favicon.png')}}" />

resources/views/user/partials/header-new.blade.php
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
	<div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
		<a class="navbar-brand brand-logo" href="#"><img src="{{asset('adminasset/images/logo.svg')}}" alt="logo"/></a>
		<a class="navbar-brand brand-logo-mini" href="#"><img src="{{asset('adminasset/images/logo-mini.svg')}}" alt="logo"/></a>
	</div>
	<div class="navbar-menu-wrapper d-flex align-items-stretch">
		<div class="search-field d-none d-md-block">
			<form class="d-flex align-items-center h-100" action="#">
				<div class="input-group">
					<div class="input-group-prepend bg-transparent">
						<i class="input-group-text border-0 mdi mdi-magnify"></i>
					</div>
					<input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
				</div>
			</form>
		</div>
		<ul class="navbar-nav navbar-nav-right">
			<li class="nav-item nav-profile dropdown">
				<a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
					<div class="nav-profile-img">
						<!-- <img src="{{asset('adminasset/images/faces/face1.jpg')}}" alt="image"> -->
						<!-- <span class="availability-status online"></span>              -->
					</div>
					<div class="nav-profile-text">
						<p class="mb-1 text-black">Admin</p>
					</div>
				</a>
				<div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
					<!-- <a class="dropdown-item" href="#">
						<i class="mdi mdi-cached mr-2 text-success"></i>
						Activity Log
					</a> -->
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">
						<i class="mdi mdi-logout mr-2 text-primary"></i>
						Signout
					</a>
				</div>
			</li>
			<li class="nav-item d-none d-lg-block full-screen-link">
				<a class="nav-link">
					<i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
				</a>
			</li>
			<!-- <li class="nav-item dropdown">
				<a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
					<i class="mdi mdi-email-outline"></i>
					<span class="count-symbol bg-warning"></span>
				</a>
				<div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
					<h6 class="p-3 mb-0">Messages</h6>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item preview-item">
						<div class="preview-thumbnail">
								<img src="{{asset('adminasset/images/faces/face4.jpg')}}" alt="image" class="profile-pic">
						</div>
						<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
							<h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>
							<p class="text-gray mb-0">
								1 Minutes ago
							</p>
						</div>
					</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item preview-item">
						<div class="preview-thumbnail">
								<img src="{{asset('adminasset/images/faces/face2.jpg')}}" alt="image" class="profile-pic">
						</div>
						<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
							<h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>
							<p class="text-gray mb-0">
								15 Minutes ago
							</p>
						</div>
					</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item preview-item">
						<div class="preview-thumbnail">
								<img src="{{asset('adminasset/images/faces/face3.jpg')}}" alt="image" class="profile-pic">
						</div>
						<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
							<h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>
							<p class="text-gray mb-0">
								18 Minutes ago
							</p>
						</div>
					</a>
					<div class="dropdown-divider"></div>
					<h6 class="p-3 mb-0 text-center">4 new messages</h6>
				</div>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
					<i class="mdi mdi-bell-outline"></i>
					<span class="count-symbol bg-danger"></span>
				</a>
				<div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
					<h6 class="p-3 mb-0">Notifications</h6>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item preview-item">
						<div class="preview-thumbnail">
							<div class="preview-icon bg-success">
								<i class="mdi mdi-calendar"></i>
							</div>
						</div>
						<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
							<h6 class="preview-subject font-weight-normal mb-1">Event today</h6>
							<p class="text-gray ellipsis mb-0">
								Just a reminder that you have an event today
							</p>
						</div>
					</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item preview-item">
						<div class="preview-thumbnail">
							<div class="preview-icon bg-warning">
								<i class="mdi mdi-settings"></i>
							</div>
						</div>
						<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
							<h6 class="preview-subject font-weight-normal mb-1">Settings</h6>
							<p class="text-gray ellipsis mb-0">
								Update dashboard
							</p>
						</div>
					</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item preview-item">
						<div class="preview-thumbnail">
							<div class="preview-icon bg-info">
								<i class="mdi mdi-link-variant"></i>
							</div>
						</div>
						<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
							<h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>
							<p class="text-gray ellipsis mb-0">
								New admin wow!
							</p>
						</div>
					</a>
					<div class="dropdown-divider"></div>
					<h6 class="p-3 mb-0 text-center">See all notifications</h6>
				</div>
			</li>
			<li class="nav-item nav-logout d-none d-lg-block">
				<a class="nav-link" href="#">
					<i class="mdi mdi-power"></i>
				</a>
			</li>
			<li class="nav-item nav-settings d-none d-lg-block">
				<a class="nav-link" href="#">
					<i class="mdi mdi-format-line-spacing"></i>
				</a>
			</li> -->
		</ul>
		<button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
			<span class="mdi mdi-menu"></span>
		</button>
	</div>
</nav>